### ISSUE TITLE
Command service init generate a not valid mesg.yml

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#244]
The command export `configuration: null` to the `mesg.yml` file that is not valid.

Use go template instead of marshal.

- Remove `visibility` and `publish`
- remove all empty variable
- add example like:
```yml
name: ERC20
description: ""
tasks:
  foo:
    name:
    outputs:
events:
  foo:
    data:
      bar:
        type: String
```
