### ISSUE TITLE
Add more detailed data in the mesg.yml

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#284]
## Problem

Right now the `mesg.yml` can only handle few types of data:
- Number
- String
- Boolean
- Object

Tho `Object` type is not really clear, it can be an object, an array, a string, whatever...

It can be confusing and we are loosing a lot of informations. We should be able to add more details

## Proposition

We need to handle 2 other kind of data, `Array` and `NestedType` and also make sure to keep the possibility to handle unstructured data.

#### Array
For the array part we could have a `repeated` attribute in the data

```yml
data:
  foo:
    type: String
    repeated: true
```

#### Nested type
For the nested type we need to be able to define the nested attributes

```yml
data:
  foo:
    type:
       attrX:
         type: String
       attrY:
         type: Number
```

#### Any
We still need to make sure that we can send any kind of data, in this case the core will not do any validation and the responsibility will be on the user to know what kind of data will be processed in the application

```yml
data:
  foo:
    type: Any
```
