### ISSUE TITLE
mesg.yml doesn't support numbers in object names.

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/core#396]
e.g. following doesn't work because test2 has a number. 

```
name: TestLogs
dependencies:
  test:
    image: nginx
  test2:
    image: nginx`
```

should we update schema to allow numbers?
