### ISSUE TITLE
Variable name validation in mesg.yml

### ISSUE THREAD

**Issue by romain-gsr** [mesg-foundation/core#508]
Here is a very small issue :

**Issue**
Classic variable names containing digits after the first character are considered invalid.

**Expected**
Classic variables names should follow the standards, e.g : 
- allow names like `a1`, `a1a`
- refuse names like `1a`.

**How to reproduce**
When defining my **mesg.yml** like this :
```yaml
name: aws-sqs
description: MESG Service to interact with AWS SQS
tasks:
  send:
    description: send a message to AWS SQS
    inputs:
      accessKeyId:
        type: String
        description: AWS access key ID
      secretAccessKey:
        type: String
        description: AWS secret access key
      region:
        type: String
        description: AWS region
      url:
        type: String
        description: url of the AWS SQS queue to which a message is sent
      body:
        type: Object
        description: message body to send
    outputs:
      success:
        data:
          MD5OfMessageBody:
            type: String
            description: MD5 digest of the non-URL-encoded message body
      error:
        data:
          message:
            type: String
```
This very line triggers an error :
```yaml
outputs:
    success:
      data:
        MD5OfMessageBody
          type: String
          description: MD5 digest of the non-URL-encoded message body
```
👉 `MD5OfMessageBody`

**Error**
<img width="748" alt="screen shot 2018-09-28 at 17 08 59" src="https://user-images.githubusercontent.com/40533586/46202543-5324a080-c341-11e8-8116-3391966b838e.png">
