### ISSUE TITLE
Variable `y` in mesg.yml triggers an error

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/core#695]
When using a key `y` like a parameter this key is interpreted as `boolean` and mess with the parsing.
This is probably related to the parsing library that we use.

Workaround is to use a different name for the variable.

`n` also have the same unexpected behavior.

Example of file with issue
```yml
name: "myservice"
sid: "test"
tasks:
  taskX:
    inputs:
      y:
        type: Object
    outputs:
      success:
        data:
          message:
            type: String
```
