### ISSUE TITLE
Improve validate of task output

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/core#800]
Related to https://github.com/mesg-foundation/service-webhook/issues/4

Currently, it's possible to have an output data in the service definition like:

```yaml
result: 
  description: "Result of the call the returns the list of the data from the API call result" 
  data: {} 
```

The core rejects when the result is emitted with error:
```
error: 'invalid output data error: json: cannot unmarshal string into Go value of type map[string]interface {}' }
```

The command `service validate` should reject to not have an data definition like this.

The proper output definition should be:
```yaml
result: 
  description: "Result of the call the returns the list of the data from the API call result" 
  data:
    data:
      type: Object
```
